---
all:
  children:
    bastion:
      hosts:
        bastion.742gt.sandbox1046.opentlc.com:
          ansible_user: rosa
          ansible_ssh_pass: "{{ bastion_ssh_password }}"
          ansible_become_password: "{{ bastion_ssh_password }}"
          ansible_python_interpreter: /usr/bin/python3
