apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: sock-shop-github-push
  namespace: microservice-app
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.ref)
