apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sock-shop-ci-manual-
  namespace: microservice-app
spec:
  pipelineRef:
    name: sock-shop-ci
  params:
    - name: repo-url
      value: https://github.com/avijra/sock-shop-rosa.git
    - name: revision
      value: main
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: sock-shop-pipeline-workspace
