apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sock-shop-pipeline-workspace
  namespace: microservice-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
